name = "CacheVariables"
uuid = "9a355d7c-ffe9-11e8-019f-21dae27d1722"
version = "0.2.1"
authors = ["David Hong <hong@udel.edu> and contributors"]

[workspace]
projects = ["test"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ExpressionExplorer = "21656369-7473-754a-2065-74616d696c43"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
BSON = "0.3.9"
Dates = "1.10"
ExpressionExplorer = "1.1.3"
JLD2 = "0.6.3"
Logging = "1.10"
MacroTools = "0.5.16"
julia = "1.10"
