name = "CacheVariables"
uuid = "9a355d7c-ffe9-11e8-019f-21dae27d1722"
authors = ["David Hong <hong@udel.edu>"]
version = "0.1.5"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
BSON = "0.3.4"
Dates = "<0.0.1, 1.0"
JLD2 = "0.4, 0.5, 0.6"
Logging = "<0.0.1, 1.0"
julia = "1.0"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames", "Test"]
