name = "CacheVariables"
uuid = "9a355d7c-ffe9-11e8-019f-21dae27d1722"
authors = ["David Hong <hong@udel.edu> and contributors"]
version = "0.2.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ExpressionExplorer = "21656369-7473-754a-2065-74616d696c43"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
BSON = "0.3.4"
Dates = "1.10"
ExpressionExplorer = "1.1.3"
JLD2 = "0.4, 0.5"
Logging = "1.10"
MacroTools = "0.5.16"
julia = "1.10"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["DataFrames", "Test", "TestItemRunner"]
